name: learn-github-actions
on: [push]
env:
  buildConfiguration: "Release"
  wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"
  dotnetSdkVersion: "5.x"
  artifactDir: "~/artifact"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Setup node
      - name: Gulp Runner
        uses: 2KAbhishek/gulp-runner@v0.3
      - uses: actions/setup-dotnet@v1
        name: Setup dotnet
        with:
          dotnet-version: ${{ env.dotnetSdkVersion }}
      - run: npm install
      - run: "./node_modules/.bin/node-sass ${{env.wwwrootDir}} --output ${{env.wwwrootDir}}"
      - run: gulp
      - run: 'echo "${{env.GITHUB_WORKFLOW}}, ${{env.GITHUB_RUN_ID}}, ${{env.GITHUB_RUN_NUMBER}}" > buildinfo.txt'
        working-directory: ${{ env.wwwrootDir }}
      - run: dotnet build **/*.Web.csproj --configuration ${{env.buildConfiguration}}
        name: "Build the project - ${{env.buildConfiguration}}"
      - run: dotnet build **/*.Tests.csproj --configuration ${{env.buildConfiguration}}
        name: "Build the test project - ${{env.buildConfiguration}}"
      - run: mkdir -p ${{env.artifactDir}}/${{env.buildConfiguration}}
      - run: dotnet publish **/*.csproj --no-build --configuration ${{env.buildConfiguration}} --output ${{env.artifactDir}}/${{env.buildConfiguration}}
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ${{env.artifactDir}}/${{env.buildConfiguration}}
