name: learn-github-actions
on: [push]

env:
  buildConfiguration: "Release"
  wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"
  dotnetSdkVersion: "5.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnetSdkVersion }}
      - run: npm install
      - run: "./node_modules/.bin/node-sass ${{ env.wwwrootDir }} --output ${{ env.wwwrootDir }}"
      - run: gulp
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test
      - run: dotnet publish -c ${{ env.buildConfiguration }} -o ${{ github.WORKSPACE }}/Release
      - uses: actions/upload-artifact@v2
        with:
          name: WebApp
          path: ${{ github.WORKSPACE }}/Release
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        run: echo "Take it from here"