name: learn-github-actions
on: [push]

runs-on: ubuntu-latest

env:
  buildConfiguration: "Release"
  wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"
  dotnetSdkVersion: "5.x"

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnetSdkVersion }}
      - run: npm install
      - run: "./node_modules/.bin/node-sass ${{ env.wwwrootDir }} --output ${{ env.wwwrootDir }}"
      - run: gulp
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet publish -c ${{ env.buildConfiguration }} -o ${{ env.GITHUB_WORKSPACE }}/Release
      - uses: actions/upload-artifact@v2
        with:
          name: WebApp
          path: ${{ env.GITHUB_WORKSPACE }}/Release